### PR TITLE
Support Firefox for iOS

### PR DESCRIPTION
**Pull request by sisidovski**
Add suport of Firefox for iOS. Test case https://github.com/woothee/woothee/pull/20
But, I don't know I should update submodule or not.

### CODE REVIEW

**Comment by yuya-takeyama** [comment]
@sisidovski 
Thank you for contribution!
Without updating submodule, your code won't be tested.
https://coveralls.io/builds/4453600/source?filename=AgentCategory%2FBrowser%2FSafariChrome.php#L33

But at frist, please wait https://github.com/woothee/woothee/pull/20 to be merged.

**Comment by sisidovski** [comment]
All right, thank you.

**Comment by sisidovski** [comment]
I updated submodule.

**Comment by yuya-takeyama** [comment]
@sisidovski 
Now it's tested correctly!
https://coveralls.io/builds/4467319/source?filename=AgentCategory%2FBrowser%2FSafariChrome.php#L33

Will merge now.

**Pull request merged**
