### PR TITLE
Catch up with woothee v1.8.0

### PR DESCRIPTION
**Pull request by tell-k**
I've catched up with woothee v1.8.0.

- Add YandexBrowser

FYI.  In my travis environment the following error was displayed.

- https://travis-ci.org/tell-k/woothee-php/jobs/406775215
- I think you need to fix .travis.ini :) 

```
PHP 5.3 is supported only on Precise.
See https://docs.travis-ci.com/user/reference/trusty#PHP-images on how to test PHP 5.3 on Precise.
```

Please feel free to merge it. Thx.

### CODE REVIEW

**Comment by hhatto** [comment]
LGTM

**Comment by tell-k** [comment]
@hhatto Thank you for your review :)
@yuya-takeyama  If possible,  Please feel free to review this PR. 🙏

**Comment by okonomi** [comment]
@tell-k @hhatto Sorry to late, I'll check soon!

**Comment by okonomi** [comment]
Merged! Thank you for the contribution.

**Pull request merged**
