### PR TITLE
Fix version

### LINKED ISSUE #23: Version is 1.1 instead of 1.2
In Tag 1.2 the Version is still 1.1

https://github.com/woothee/woothee-php/blob/v1.2.0/src/Classifier.php#L35

### PR DESCRIPTION
**Pull request by yuya-takeyama**
Fixes #23

### CODE REVIEW

**Comment by tagomoris** [comment]
:+1:

**Comment by yuya-takeyama** [comment]
I'm considering

* How to prevent recurrence
* Whether I should replace the 1.2.0 on Packagist

**Comment by tagomoris** [comment]
IMO bumping version up to `v1.2.1` is best option for consistency.
Patch versions are reserved for package maintenance of each language implementations.

**Comment by yuya-takeyama** [comment]
@tagomoris 
Thanks!
So I'll do like below.

* Bump version to 1.2.1
* Release as v1.2.1

**Comment by yuya-takeyama** [comment]
@tagomoris 
I've read this.
https://github.com/woothee/woothee#versions

>Version numbers are used as:
* vX.Y.Z
  * X and Y is major/minor number to control specs of dataset/testsets
  * Z is patch number for each language implementation release control
  * Z is also used for bug fix control of testsets (versions of each language implementations should be bumped up too)

So next time `woothee/woothee` testsets will be released, the version is `1.2.2`?

**Comment by tagomoris** [comment]
@yuya-takeyama "bug fix of testsets" are only for cases unexpected, and trivial. So patch version sync of each implementations (and `woothee/woothee` itself) is out of my concerns. `woothee/woothee` next version may be `1.2.1`, but `woothee-php` can be released as `1.2.2`.

**Comment by yuya-takeyama** [comment]
@woothee/woothee-php-team 
I've fixed the version not `1.2.0` but `1.2.1` to follow @tagomoris' advice. https://github.com/woothee/woothee-php/pull/27#issuecomment-156792173

Please merge if you are happy with it!

After that, I'll release it as `v1.2.1` to Packagist.

**Comment by tagomoris** [comment]
@yuya-takeyama Merged. Sorry for late operation.

**Pull request merged**
