### PR TITLE
v1.2.0

### PR DESCRIPTION
**Pull request by yuya-takeyama**
* Support Twitterbot
* Support Windows10
* Support MS Edge
* Support Webview
* Support BlackBerry10
* Run test against PHP 7 and it's passed!

### CODE REVIEW

**Comment by okonomi** [comment]
LGTM:star2:

**Comment by yuya-takeyama** [comment]
Thanks!
I'll release this later.

**Comment by yuya-takeyama** [comment]
@tagomoris @okonomi 
Just released!
https://packagist.org/packages/woothee/woothee

**Comment by okonomi** [comment]
@yuya-takeyama :clap::clap::clap:

**Comment by tagomoris** [comment]
yay! :clap:

**Pull request merged**
